### ISSUE TITLE
I stay trying this in stm32f469 disco with issue in flash moment with openocd command

### ISSUE THREAD

**Issue by neuberfran** [arthurggordon/emb-rust#2]
Hi,

I have stm32f469 disco kit and I stay trying blink led using this project

Error: open failed
in procedure 'init' 
in procedure 'ocd_bouncer'

![Screenshot from 2023-08-01 16-55-22](https://github.com/arthurggordon/emb-rust/assets/38701397/d120a6fc-9ad2-4956-b4f6-80a8552c2c86)
Pls help-me
Cheers

**Comment by arthurggordon** [comment]
Looks like you are using a completely different board :
https://www.st.com/en/evaluation-tools/32f469idiscovery.html
This board that you have has 2Mbytes of Flash and 324 Kbytes of RAM.

This project used: https://www.st.com/en/evaluation-tools/stm32f4discovery.html
This board has 1Mbytes of Flash and 192 Kbytes of RAM.

As a starting point you could try setting the correct parameters in the `memory.x` file for the larger memory. 

Also it appears that the dependencies have been updated since this project was written, see https://github.com/stm32-rs/stm32f4xx-hal/tree/master

**Comment by neuberfran** [comment]
@arthurggordon I can with sudo openocd -f interface/stlink-v2-1.cfg -f target/stm32f4x.cfg.

But

Now I need your help to change your code so that the onboard led (from stm32f469 disco) and only that led, blink every second

![20230801_175039](https://github.com/arthurggordon/emb-rust/assets/38701397/47cee8da-e190-465f-9212-10a9b28e7d57)

**Comment by arthurggordon** [comment]
I can't help, I know nothing about that board.

**Comment by neuberfran** [comment]
I don't need your help
